#!/usr/bin/env python

import CedrusSConsDefaultEnvironments
import CedrusSConsHelperFunctions

import os
import sys

env_settings = {'MSVC_VERSION': '14.0'}
env = CedrusSConsDefaultEnvironments.PerformCedrusSConsGlobalGeneralStartup(env_settings)

# should compute a path like: /Users/ematsak/source/xid_device_library
# (it should be where you CLONED the project: git@github.com:cedrus-opensource/xid_device_library.git)
outer_repo_root_dir = os.path.abspath( os.getcwd() ) + os.path.sep + '..' + os.path.sep
env['XIDLIB_OUTER_REPO_DIR'] = outer_repo_root_dir

#os.environ['GMOCK'] = outer_repo_root_dir + 'binaries_gtest'
env['WX_VERSION'] = 'NONE'
projects = [
    'SConscript.xid_device_driver',
    'SConscript.st_tester',
    #'SConscript.TestXidLib', # this is commented out for the general public. the SConscript can be enabled at Cedrus.
]

env.Replace(
    CEDRUS_LISTING_OF_BUILD_SCONSCRIPTS = projects,
    TARGET_ARCH='x86'
)

if GetOption('build_mode') == 'opt':
    env.AppendUnique( CPPDEFINES = [ 'CEDRUS_DISABLE_ASSERT' ] )

env[ 'CURRENT_CEDRUS_REPO_ROOT' ] = sys.path[0] + '/../'
print 'Setting repo root to: ' + env[ 'CURRENT_CEDRUS_REPO_ROOT' ]

env.Repository( env[ 'CURRENT_CEDRUS_REPO_ROOT' ] )

def BuildEnvironmentSConscripts(masterConfig):

    for c in masterConfig['CEDRUS_LISTING_OF_BUILD_SCONSCRIPTS']:
        # Clone the environment so components can't interfere with each other
        ec = masterConfig.Clone()

        # The component is a SConscript file.
        c_script = ec.File(c)
        c_dir = c_script.dir # c_dir is important for the scripts in COMMON (not here side-by-side in our scons dir)

        variant_dir_string = '$OBJ_ROOT/' + str(c_dir)

        if sys.platform == 'win32' and str(c_dir) != '.':
            variant_dir_string = '$OBJ_ROOT/Cmv_dir_win32/dir_' + str(c_script.name) + '/'

        #print ec.subst( variant_dir_string )
        ec['CEDRUS_CHOSEN_VARIANT_DIR'] = variant_dir_string

        ec.SConscript(c_script,
                      variant_dir=variant_dir_string,
                      exports={'env': ec},   # this is why each SConscript has a line like: Import('env')
                      duplicate=0 # Sometimes I find it helpful to COMMENT THIS OUT for diagnosing scons issues
                      )

env = CedrusSConsDefaultEnvironments.GetDefaultSetupForCurrentSystemAndCommandLine( env )

print 'Name of selected build environment: ' + str(env['BUILD_TYPE_DESCRIPTION'])
BuildEnvironmentSConscripts(env)
